### ISSUE TITLE
idevicerestore.exe -e -l command is failing on sending iBEC in window 10.

### ISSUE THREAD

**Issue by ashishgah** [libimobiledevice/libimobiledevice#1303]
below error is coming:-

Sending iBEC (947259 bytes)...
ERROR: Unable to send iBEC component: Unable to find device
ERROR: Unable to send iBEC to device.
ERROR: Unable to send iBEC

**Comment by mexmer** [comment]
from error it looks, either device is not connected in restore mode, or you didn't supply correct udid of target device

**Comment by nikias** [comment]
I merged a PR regarding timeouts for recovery mode device detection, kindly give it a try with the latest code. Maybe it works now.

**Comment by ashishgah** [comment]
Hello sir,

actually this error only comes when it finds iBoot driver in Device Manager like below:-

Apple Recovery (iBoot) USB Composite Device.

when i manually uninstall this driver, idevicerestore runs fine but my question is that can we run idevicerestore without manually uninstalling iBoot driver.  

every time when it finds iBoot driver, idevicerestore fails on sending iBec.

**Comment by ashishgah** [comment]
Hello @nikias sir, i tried latest code but iBec error is still coming.

actually this error only comes when it finds iBoot driver in Device Manager like below:-

Apple Recovery (iBoot) USB Composite Device.

when i manually uninstall this driver, idevicerestore runs fine but my question is that can we run idevicerestore without manually uninstalling iBoot driver.

every time when it finds iBoot driver under Universal Serial Bus devices, idevicerestore fails on sending iBec.

**Comment by mexmer** [comment]
> Hello @nikias sir, i tried latest code but iBec error is still coming.
> 
> actually this error only comes when it finds iBoot driver in Device Manager like below:-
> 
> Apple Recovery (iBoot) USB Composite Device.
> 
> when i manually uninstall this driver, idevicerestore runs fine but my question is that can we run idevicerestore without manually uninstalling iBoot driver.
> 
> every time when it finds iBoot driver under Universal Serial Bus devices, idevicerestore fails on sending iBec.

since you talking about uninstalling drivers, i will assume, you are using windows.
when removing driver, make sure you mark checkbox "also uninstall driver", that way, driver is removed from windows drivers repository, and should not go back, unless that driver is available on windows update servers.

when apple added itunes microsoft store app, they also added into windows update repository winusb based drivers for apple devices, which windows 10 install automatically, when you connect apple device.

there is also other version of drivers (IOCTL based), that is shipped with desktop version of itunes ...

there also exist 3rd party driver for apple device, used by some tools, that do not rely on itunes.

**Comment by ashishgah** [comment]
Exactly, i am using windows. 

And my need is that, i can not uninstall driver manually. So there is any way or changes in libimobiledevice so that i can restore iphone without manually uninstalling iboot driver.

**Comment by mexmer** [comment]
> Exactly, i am using windows.
> 
> And my need is that, i can not uninstall driver manually. So there is any way or changes in libimobiledevice so that i can restore iphone without manually uninstalling iboot driver.

on windows libimobile uses applemobiledeviceservice (which is equivalent of usbmuxd on linux), libimobile and libirecovery (or respective tools that using them) query this service for list of connected devices, they do not directly communicate with device.

so if service doesn't recognize device, there is nothing that libimobiledevice can do about that, which can indeed happen, if you use wrong driver.
first, you should check if you can see your device (in recovery mode), in itunes windows application, if it's not there. then idevicerecory will not see it either.

**Comment by hiepnh0** [comment]
> > Exactly, i am using windows.
> > And my need is that, i can not uninstall driver manually. So there is any way or changes in libimobiledevice so that i can restore iphone without manually uninstalling iboot driver.
> 
> on windows libimobile uses applemobiledeviceservice (which is equivalent of usbmuxd on linux), libimobile and libirecovery (or respective tools that using them) query this service for list of connected devices, they do not directly communicate with device.
> 
> so if service doesn't recognize device, there is nothing that libimobiledevice can do about that, which can indeed happen, if you use wrong driver. first, you should check if you can see your device (in recovery mode), in itunes windows application, if it's not there. then idevicerecory will not see it either.

iTunes restore iphone without manually uninstalling iboot driver!

**Comment by deyvs02** [comment]
> Exactly, i am using windows.
> 
> And my need is that, i can not uninstall driver manually. So there is any way or changes in libimobiledevice so that i can restore iphone without manually uninstalling iboot driver.

can you give me the idevicerestore.exe file because what I have is the 2019 version and every time I start the restore when I get to the middle of the process it shows me an error data not found
